apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssid-email-lookup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssid-email-lookup
  template:
    metadata:
      labels:
        app: ssid-email-lookup
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ssid-email-lookup
          image: ghcr.io/wstrzelec/ssid-email-lookup:v0.1.0 # {"$imagepolicy": "flux-system:ssid-email-lookup"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
